{% set name = "starship" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 480fa3887041e4d6297970fda7cfbf3032b7f8626c7a20f11d86d37aaf2766f1

build:
  number: 0
  skip: true  # [linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}

test:
  commands:
    - starship -h

about:
  home: https://starship.rs/
  license: ISC
  license_file: LICENSE
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
  dev_url: https://github.com/starship/starship

extra:
  recipe-maintainers:
    - m-rossi
