{% set name = "starship" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8340b8b7a4b75c17f3f72c6a4a81a8470c003719594f6884b151490a9433461b

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - sysroot_linux-64 2.17  # [linux64]

test:
  commands:
    - starship -h

about:
  home: https://starship.rs/
  license: ISC
  license_file: LICENSE
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
  dev_url: https://github.com/starship/starship

extra:
  recipe-maintainers:
    - m-rossi
