{% set name = "starship" %}
{% set version = "1.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ea73a5463d30c5d5dfd473b11a27f2f25942635121dc3fc89297eeb22755ce8f

build:
  number: 0
  ignore_run_exports:
    - libcxx  # [osx]
    - libstdcxx-ng  # [linux]
    - vs2015_runtime  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - make  # [linux]
    - cmake  # [not win]
    - cargo-bundle-licenses
  run:

test:
  commands:
    - starship -h

about:
  home: https://starship.rs/
  license: ISC
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
  dev_url: https://github.com/starship/starship

extra:
  recipe-maintainers:
    - m-rossi
