{% set name = "starship" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3f29cb6e5cb7c673cbc1f8e91ceb4a0d1317d235b147db15e461ffec22be13a5

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - sysroot_linux-64 2.17  # [linux64]

test:
  commands:
    - starship -h

about:
  home: https://starship.rs/
  license: ISC
  license_file: LICENSE
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
  dev_url: https://github.com/starship/starship

extra:
  recipe-maintainers:
    - m-rossi
