{% set name = "starship" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 28730f76858cddc371666b526a50905d75f7a820ca7a2b974822789f92aed2fe

build:
  number: 0
  ignore_run_exports:
    - libcxx  # [osx]
    - libstdcxx-ng  # [linux]
    - vs2015_runtime  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake  # [not win]
    - sysroot_linux-64 2.17  # [linux64]
    - cargo-bundle-licenses
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.10") }}  # [osx and x86_64]

test:
  commands:
    - starship -h

about:
  home: https://starship.rs/
  license: ISC
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
  dev_url: https://github.com/starship/starship

extra:
  recipe-maintainers:
    - m-rossi
