{% set name = "starship" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4b10562954e42e8e75b1a82fbe9484b8126735e610d8aec3366c7a98651e5898

build:
  number: 0
  skip: true  # [linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}

test:
  commands:
    - starship -h

about:
  home: https://starship.rs/
  license: ISC
  license_file: LICENSE
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
  dev_url: https://github.com/starship/starship

extra:
  recipe-maintainers:
    - m-rossi
