{% set name = "starship" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 158003cd192f9375e504b9ab84d9239a06a8f9732cdd201243ab2fdcd38043f8

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - sysroot_linux-64 2.17  # [linux64]
    - cargo-bundle-licenses

test:
  commands:
    - starship -h

about:
  home: https://starship.rs/
  license: ISC
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
  dev_url: https://github.com/starship/starship

extra:
  recipe-maintainers:
    - m-rossi
